### ISSUE TITLE
It sending 1 message only after that need login again.

### ISSUE THREAD

**Issue by draj14dec** [vijay38/Whatsapp-Automation#1]
its good program i used on google chrome It sending 1 message only after that need login again.it only pick only 1 pic if i have 10 or 20 pic then what is the solution.
Please guide me so i try.

**Comment by vijay38** [comment]
Using this You can send a **single** message message to many people at a time. So if you want to send multiple messages,then there are 2 things to consider.

1. Sending multiple messages to **N** Same people
2. Sending multiple messages to multiple  people(People may vary for each message)

If it's the case 1 you can send all text as a single message as all the people are same, all messages will be sent in a single Go.
But if it's the case 2 you have to give the list of numbers to whom you want to send for each message.
Because you are asked to give list of numbers to whom you want to send the given message so you have to do it multiple times if the numbers are different.

Coming to images,the concept how image appear on whatsapp is that  **CTRL+V** is pressed by pyautogui when there is a image is to be sent.So there should be a image in the clipboard at top to send that image.
Generally when we **CTRL+C** an image they are not stored in clipboard. So we are sending image to clipboard by python(Line 164).

when we press **CTRL+V** only the top item in clipboard will be loaded in message .

So In order to send multiple images the solution is that you must send the images to clipboard one by one.One should sent to clipboard after previous image is successfully loaded on whatsapp web. Writing a for loop can solve your problem.

Hope your problem is solved.If not please mention the problem.Thank you!
